version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.3.3-java11
    networks:
      - hbase
    volumes:
      - ${HADOOP_NAME_NODE_VOLUME}:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - ${HADOOP_NAME_NODE_PORT}:${HADOOP_NAME_NODE_PORT}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == akswnc4.aksw.uni-leipzig.de
      labels:
        traefik.docker.network: hbase
        traefik.port: ${HADOOP_NAME_NODE_PORT}

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.3.3-java11
    networks:
      - hbase
    volumes:
      - ${HADOOP_DATA_NODE_VOLUME}:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: namenode:${HADOOP_NAME_NODE_PORT}
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: hbase
        traefik.port: ${HADOOP_DATA_NODE_PORT}

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.3.3-java11
    networks:
      - hbase
    environment:
      SERVICE_PRECONDITION: "namenode:${HADOOP_NAME_NODE_PORT} datanode:${HADOOP_DATA_NODE_PORT}"
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == akswnc4.aksw.uni-leipzig.de
      labels:
        traefik.docker.network: hbase
        traefik.port: ${HADOOP_RESOURCE_MANAGER_PORT}
    healthcheck:
      disable: true

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.3.3-java11
    networks:
      - hbase
    environment:
      SERVICE_PRECONDITION: "namenode:${HADOOP_NAME_NODE_PORT} datanode:${HADOOP_DATA_NODE_PORT} resourcemanager:${HADOOP_RESOURCE_MANAGER_PORT}"
    env_file:
      - ./hadoop.env
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: hbase
        traefik.port: 8042

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.3.3-java11
    networks:
      - hbase
    volumes:
      - ${HADOOP_HISTORY_SERVER_VOLUME}:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:${HADOOP_NAME_NODE_PORT} datanode:${HADOOP_DATA_NODE_PORT} resourcemanager:${HADOOP_RESOURCE_MANAGER_PORT}"
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == akswnc4.aksw.uni-leipzig.de
      labels:
        traefik.docker.network: hbase
        traefik.port: ${HADOOP_HISTORY_SERVER_PORT}

networks:
  hbase:
    name: hbase
    driver: bridge

